### ISSUE TITLE
AIR 33.1.1.533 - Quick Complie doesn't work.

### ISSUE THREAD

**Issue by everseen83** [BowlerHatLLC/vscode-as3mxml#538] opened 2021-07-03 16:10 UTC
current OS - mac Big Sur (not m1)

[ Error Massage ]
Error launching SWF debug session. Process exited with code: 10 
invalid profile specified 'Profile not supported'

There is no problem with compiling in lower version of SDK.(33.1.1.406, 444, etc)
Can you help me to solve that problem?

**Comment by joshtynjala** [comment] 2021-07-08 18:45
Confirmed that the latest AIR 33.1 builds are not working with the debugger. I get different error messages with different versions, though.

AIR 33.1.1.476:

```
Error launching SWF debug session.
flash.tools.debugger.VersionException: Unexpected version of the Flash Player
at flash.tools.debugger.concrete.PlayerSession.bind(PlayerSession.java:384)
at flash.tools.debugger.threadsafe.ThreadSafeSession.bind(ThreadSafeSession.java:81)
at com.as3mxml.vscode.SWFDebugSession.launch(SWFDebugSession.java:676)
at com.as3mxml.vscode.debug.DebugSession.dispatchRequest(DebugSession.java:104)
at com.as3mxml.vscode.debug.protocol.ProtocolServer.dispatch(ProtocolServer.java:143)
at com.as3mxml.vscode.debug.protocol.ProtocolServer.processData(ProtocolServer.java:102)
at com.as3mxml.vscode.debug.protocol.ProtocolServer.start(ProtocolServer.java:81)
at com.as3mxml.vscode.SWFDebug.main(SWFDebug.java:49)
```

AIR 33.1.1.533:

```
Error launching SWF debug session. Process exited with code: 10

Process terminated without establishing connection to debugger.

invalid profile specified 'Profile not supported'
```

I'm not sure that there's anything I can do, though.

**Comment by joshtynjala** [comment] 2021-07-08 19:15
It seems to be the `mobileDevice` profile that 533 doesn't like. I can get it to launch with the `desktop` profile.

**Comment by joshtynjala** [comment] 2021-07-08 19:15
It seems to be fixed on Harman's side, and will be in the next release.

https://github.com/airsdk/Adobe-Runtime-Support/issues/950#issuecomment-874572997

**Closed by joshtynjala** 2021-07-08 19:15 UTC
Labels: bug
