### ISSUE TITLE
Show simple error if main app file is moved or renamed

### ISSUE THREAD

**Issue by neminovno** [BowlerHatLLC/vscode-as3mxml#227] opened 2018-06-17 13:21 UTC
If main app file, for example _Main.mxml_, is moved or renamed, these 3 problems appear:

> Internal error in syntax tree request subsystem, when generating code for: c:\dev\project\src\Main.mxml: java.lang.ArrayIndexOutOfBoundsException: 0
> 	at org.apache.royale.compiler.internal.units.MXMLCompilationUnit.handleSyntaxTreeRequest(MXMLCompilationUnit.java:89)
> 	at org.apache.royale.compiler.internal.units.CompilationUnitBase.processSyntaxTreeRequest(CompilationUnitBase.java:838)
> 	at org.apache.royale.compiler.internal.units.CompilationUnitBase.access$100(CompilationUnitBase.java:108)
> 	at org.apache.royale.compiler.internal.units.CompilationUnitBase$2$1.call(CompilationUnitBase.java:262)
> 	at org.apache.royale.compiler.internal.units.CompilationUnitBase$2$1.call(CompilationUnitBase.java:258)
> 	at org.apache.royale.compiler.internal.units.requests.RequestMaker$1.call(RequestMaker.java:228)
> 	at org.apache.royale.compiler.internal.units.requests.RequestMaker$1.call(RequestMaker.java:222)
> 	at java.util.concurrent.FutureTask.run(Unknown Source)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> 	at java.lang.Thread.run(Unknown Source)
> 
> 
> Internal error in file scope builder subsystem, when generating code for: c:\dev\project\src\Main.mxml: java.lang.NullPointerException: Null value not allowed in cache store.
> 	at org.apache.royale.compiler.internal.caches.ConcurrentCacheStoreBase.get(ConcurrentCacheStoreBase.java:71)
> 	at org.apache.royale.compiler.internal.mxml.MXMLDataManager.get(MXMLDataManager.java:52)
> 	at org.apache.royale.compiler.internal.mxml.MXMLDataManager.get(MXMLDataManager.java:36)
> 	at org.apache.royale.compiler.internal.units.MXMLCompilationUnit.getMXMLData(MXMLCompilationUnit.java:281)
> 	at org.apache.royale.compiler.internal.units.MXMLCompilationUnit.handleFileScopeRequest(MXMLCompilationUnit.java:168)
> 	at org.apache.royale.compiler.internal.units.CompilationUnitBase.processFileScopeRequest(CompilationUnitBase.java:863)
> 	at org.apache.royale.compiler.internal.units.CompilationUnitBase.access$200(CompilationUnitBase.java:108)
> 	at org.apache.royale.compiler.internal.units.CompilationUnitBase$3$1.call(CompilationUnitBase.java:287)
> 	at org.apache.royale.compiler.internal.units.CompilationUnitBase$3$1.call(CompilationUnitBase.java:283)
> 	at org.apache.royale.compiler.internal.units.requests.RequestMaker$1.call(RequestMaker.java:228)
> 	at org.apache.royale.compiler.internal.units.requests.RequestMaker$1.call(RequestMaker.java:222)
> 	at java.util.concurrent.FutureTask.run(Unknown Source)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> 	at java.lang.Thread.run(Unknown Source)
> 
> 
> Internal error in outgoing dependency subsystem, when generating code for: c:\dev\project\src\Main.mxml: java.lang.NullPointerException
> 	at org.apache.royale.compiler.internal.units.CompilationUnitBase.startParsingImports(CompilationUnitBase.java:909)
> 	at org.apache.royale.compiler.internal.units.MXMLCompilationUnit.handleOutgoingDependenciesRequest(MXMLCompilationUnit.java:240)
> 	at org.apache.royale.compiler.internal.units.CompilationUnitBase.processOutgoingDependenciesRequest(CompilationUnitBase.java:891)
> 	at org.apache.royale.compiler.internal.units.CompilationUnitBase.access$500(CompilationUnitBase.java:108)
> 	at org.apache.royale.compiler.internal.units.CompilationUnitBase$6$1.call(CompilationUnitBase.java:387)
> 	at org.apache.royale.compiler.internal.units.CompilationUnitBase$6$1.call(CompilationUnitBase.java:383)
> 	at org.apache.royale.compiler.internal.units.requests.RequestMaker$1.call(RequestMaker.java:228)
> 	at org.apache.royale.compiler.internal.units.requests.RequestMaker$1.call(RequestMaker.java:222)
> 	at java.util.concurrent.FutureTask.run(Unknown Source)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> 	at java.lang.Thread.run(Unknown Source)

It would be better if there is only one problem like the one when _asconfig.json_'s `files` is edited:

> Main.mxml is not located in the project's source path. Code intelligence will not be available for this file.

**Comment by joshtynjala** [comment] 2018-07-30 20:30
I am able to reproduce this issue with a main *.mxml* file, but not with a main *.as* file.

With a main *.mxml* file, I can see an additional exception being thrown in the compiler's background thread.

> java.io.FileNotFoundException: c:\Users\josht\Development\as3mxml\examples\HelloClassicFlex\src\HelloClassicFlex.mxml
>	at org.apache.royale.compiler.filespecs.FileSpecification.createReader(FileSpecification.java:79)
>	at org.apache.royale.compiler.internal.caches.MXMLDataCache.createEntryValue(MXMLDataCache.java:85)
>	at org.apache.royale.compiler.internal.caches.MXMLDataCache.createEntryValue(MXMLDataCache.java:38)
>	at org.apache.royale.compiler.internal.caches.ConcurrentCacheStoreBase.get(ConcurrentCacheStoreBase.java:69)
>	at org.apache.royale.compiler.internal.mxml.MXMLDataManager.get(MXMLDataManager.java:52)
>	at org.apache.royale.compiler.internal.mxml.MXMLDataManager.get(MXMLDataManager.java:36)
>	at org.apache.royale.compiler.internal.units.MXMLCompilationUnit.getMXMLData(MXMLCompilationUnit.java:281)
>	at org.apache.royale.compiler.internal.units.MXMLCompilationUnit.handleFileScopeRequest(MXMLCompilationUnit.java:168)
>	at org.apache.royale.compiler.internal.units.CompilationUnitBase.processFileScopeRequest(CompilationUnitBase.java:863)
>	at org.apache.royale.compiler.internal.units.CompilationUnitBase.access$200(CompilationUnitBase.java:108)
>	at org.apache.royale.compiler.internal.units.CompilationUnitBase$3$1.call(CompilationUnitBase.java:287)
>	at org.apache.royale.compiler.internal.units.CompilationUnitBase$3$1.call(CompilationUnitBase.java:283)
>	at org.apache.royale.compiler.internal.units.requests.RequestMaker$1.call(RequestMaker.java:228)
>	at org.apache.royale.compiler.internal.units.requests.RequestMaker$1.call(RequestMaker.java:222)
>	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>	at java.lang.Thread.run(Thread.java:748)

This is definitely a royale-compiler bug. It should be outputting errors more like these (which is what I see when I rename a main *.as* file):

> File not found: c:\Users\josht\Development\as3mxml\examples\HelloClassicFlex\src\HelloClassicFlex.mxml
> No externally-visible definition with the name 'HelloClassicFlex' was found.

**Comment by joshtynjala** [comment] 2019-04-12 21:04
Closing because this appears to be working correctly now.

**Closed by joshtynjala** 2019-04-12 21:04 UTC
Labels: bug, royale-dependency
