### ISSUE TITLE
Intellisense only working for a few seconds

### ISSUE THREAD

**Issue by cgascons** [BowlerHatLLC/vscode-as3mxml#509] opened 2020-11-16 08:43 UTC
Hi, for some reason the Intellisense autocompletion only works for the first few seconds (~30s) after opening a new project. Afterworks it will hang and only shows the "Loading" tooltip where the box with suggestions should appear. I also noticed the editor footer message "_Initialising ActionScript & MXML language server_" stays there for a really long time.

Besides this, not sure if related but after a few attempts to use the editor (launch the game, close it, edit code, compile and relaunch and so on) it seems that many java processes are being created and never killed automatically by vscode, which ends up slowing down my mac to the point of having to manually kill them to be able to continue working. 

![image](https://user-images.githubusercontent.com/2189330/99230898-2ae1af80-27f0-11eb-95ba-4d06c816a7c7.png)

**Comment by joshtynjala** [comment] 2020-11-16 17:13
> I also noticed the editor footer message "Initialising ActionScript & MXML language server" stays there for a really long time.

But it eventually disappears, right?

**Comment by joshtynjala** [comment] 2020-11-16 17:14
When this happens, can you open the "Output" view in VSCode, and switch the drop down to "ActionScript & MXML Language Server" and copy/paste any error messages that you find in there?

**Comment by cgascons** [comment] 2020-11-17 08:11
> But it eventually disappears, right?

That's correct, after a few seconds its' gone.



> When this happens, can you open the "Output" view in VSCode, and switch the drop down to "ActionScript & MXML Language Server" and copy/paste any error messages that you find in there?

Tried to do this today, no luck. The output tab is empty. What I noticed anyways is something related to this issue I found [here](https://github.com/BowlerHatLLC/vscode-as3mxml/issues/205). It looks like as I type some code the _Problems_ tab gets filled with hundreds of issues, then after a few seconds gets back to normal, like if it was trying to compile the whole project every time I type a character. It's weird because that issue appears as closed and should not be happening.

It's worth noting that I'm dealing with a quite big project, which depends on custom libraries, in this particular case this project is using 3 custom libraries (added to workspace as well), perhaps is having a hard time because of that?

Hope this info helps in any way.

**Comment by joshtynjala** [comment] 2020-11-17 18:29
It's interesting that hundreds of problems appear. I would expect maybe a few at most while typing, since you'll have bad syntax for a short time between certain characters, but not hundreds. That does indeed make it seem like it's trying to compile your whole project from scratch. However, typing in a single file should not cause the whole project to be re-validated. Part of my fix for #205 was to focus only on the current file, and then check the rest of the project on save.

Your issue sounds to me like it's #420 instead. That is still unsolved because no one has been able to share a project with me to try to reproduce it on my Mac. All of my own projects are working correctly on that machine.

**Comment by cgascons** [comment] 2020-11-18 08:26
I understand, I will try to create a sample project to replicate this issue.

**Comment by cgascons** [comment] 2020-11-18 09:40
By the way I did not tell you, it does look like indeed we are facing the same issue stated in https://github.com/BowlerHatLLC/vscode-as3mxml/issues/420. I have anyways (in case it helps somehow), gathered a sample of the stuck/high cpu java process in the Activity monitor as seen here:

![image](https://user-images.githubusercontent.com/2189330/99512258-8c895180-2989-11eb-8795-568ba7bbf58e.png)

And this [this](https://github.com/BowlerHatLLC/vscode-as3mxml/files/5559118/java_sample.txt) is the sample text received (could not add the sample text here because the it exceeds the maximum characters for a comment). Notice that I'm using java 1.8.0 for this specific project but it also happens when using newer versions of java, I will try today if this happens as well with a different computer.

**Comment by joshtynjala** [comment] 2020-11-18 17:21
> By the way, today I did get some info in the Output tab, here it is:

Thanks! Unfortunately, this is just normal behavior.

Hoping you can put together a sample project. At the very least, your asconfig.json might have some clues, but a full project would be ideal.

**Comment by cgascons** [comment] 2020-11-19 08:24
I will definitely try to make that sample project for you. In the meantime the asconfig.json I'm currently using is the same that I pasted on a past issue here https://github.com/BowlerHatLLC/vscode-as3mxml/issues/388#issuecomment-708562425, in case it helps you find something while I try to replicate this on a smaller project.

**Comment by joshtynjala** [comment] 2020-11-19 17:25
Thanks. There are a couple of interesting things in your asconfig.json that I can play around with to try to reproduce the issue. FRESteamWorks.ane is specified three different times in the compiler options. Plus, its parent folder is specified twice, meaning that it is might actually be referenced five times. You have a "\n" character in additionalOptions, which I wouldn't have expected that to work at all, and it might be having side effects. Tomorrow is my day to work on VSCode stuff, so I'll check it out then.

**Comment by joshtynjala** [comment] 2020-11-20 20:49
I did some more investigating this morning. Unfortunately, I still don't know how to reproduce on my Mac. However, I did find a code path that is most likely the cause of this behavior:

> It looks like as I type some code the Problems tab gets filled with hundreds of issues, then after a few seconds gets back to normal, like if it was trying to compile the whole project every time I type a character.

In the extension, there's a didChange() method that is called whenever you change the contents of an editor in VSCode. Normally, it can successfully find a "compilation unit" for the specified file path, and everything works great. If there is no compilation unit for a file path, it tries to compile the whole project, and that should create the missing compilation unit. Again, everything should be great after that. What seems to be happening is that the compilation unit is never getting created (or maybe the file path doesn't quite match up, for some reason). Once I am able to reproduce, this method should be a good place for me to find some more clues.

**Comment by cgascons** [comment] 2020-11-23 08:20
> Once I am able to reproduce, this method should be a good place for me to find some more clues.

Thank you very much for looking into this. I will try to find time this week to make a replicable project though is going to be difficult because I also believe it only happens on large projects. 

Funny thing though, if I leave the project long enough open after editing it, there's a moment where the intellisense auto-complete seems to re-activate by itself and starts working for a few seconds, not crucial but I thought I'd let you know.

**Comment by cgascons** [comment] 2020-11-23 15:16
Correct me if I'm wrong, is the extension continuously re-compiling all the linked projects and libraries every time I edit code? In case it is, I believe that may be contributing to the issue and making the whole process slower.

**Comment by joshtynjala** [comment] 2020-11-23 17:03
> Funny thing though, if I leave the project long enough open after editing it, there's a moment where the intellisense auto-complete seems to re-activate by itself and starts working for a few seconds, not crucial but I thought I'd let you know.

Thanks. At least we can be sure that it's not stuck in an infinite loop somewhere.

> Correct me if I'm wrong, is the extension continuously re-compiling all the linked projects and libraries every time I edit code? In case it is, I believe that may be contributing to the issue and making the whole process slower.

It's designed to recompile only what has changed. Only the class you are editing, and maybe some things that directly depend on the class. The problem with your project is that the extension is asking the compiler for a specific class in compiled form, and the compiler doesn't seem to have it. So it tries to recompile the whole project, which takes a long time. Then, it still can't find the class, so it keeps trying the same thing. To be clear, it should only need to do that once, so I'm trying to figure out what is making it fail repeatedly.

**Comment by cgascons** [comment] 2020-12-02 08:56
Hi Josh, just wanted to let you know I haven't forgotten about this issue and as soon as I get the time I will create a test project to make it easier for you to replicate the error on your end, we are just finishing an expansion to be released next week and couldn't find the time to do it yet.

**Comment by cgascons** [comment] 2020-12-16 10:17
Hi Josh. 

I've been trying to create a sample project for you these last two days and I just can't seem to be able to replicate this issue on a test project. 

I have some clues that might be interesting for you though. 

The only way I experience this issue is by editing the custom engine we built for our trading card games, it's a quite big project, that's why I believe it's being so difficult to replicate creating small sample projects. I have tried testing by downloading big open source projects without luck.

I have installed the VSCodeCounter extension to check how large is the project in class and lines amount and (just in case it helps) it's **676 classes** summing up **338.434 lines of code**. 

Still, I don't believe it's just the lines of code or the amount of classes, but how it's structured internally. Please let me know if this makes sense: in our current project we have a class called the `InstanceMng`. This class basically has references to all classes in game, i.e. we use it to get instances of all our managers. Each Manager class has lots of references (imports) to the more (small) classes so I'm kind of seeing here a `tree` structure here. Could the issue here is that the plugin is somehow recursively looping through these classes if they are connected (have imports to each other)? I know this may sound weird but it's as far as I could get. Perhaps you have access to a very large project that has a similar structure?

**Comment by joshtynjala** [comment] 2020-12-16 16:50
I don't think that it has anything to do with how your code depends on other classes or imports things. I think it is related to how your project or workspace is configured in some way.

I have one especially large workspace with 4 apps and 6 library projects that is probably comparable in terms of number of classes, but I have not been able to reproduce this issue with that one.

A couple of things to try:

1) Have you tried increasing the memory used by the extension with the [`as3mxml.languageServer.jvmargs`](
as3mxml.languageServer.jvmargs) setting? Since it's a large project, more memory may help. I think Java chooses a default size based on your computer specs, so I don't know what the default is. It's the -Xmx arg. Maybe try -Xmx1024m or -Xmx2048m.

2) In the latest update, I added the [`as3mxml.languageServer.concurrentRequests`](https://github.com/BowlerHatLLC/vscode-as3mxml/wiki/Extension-settings#as3mxmllanguageserverconcurrentrequests) setting. Can you try changing this to false? Then, close and restart VSCode. If this helps, we can be sure that this is a multi-threading issue. If not, then we can rule that out.

**Comment by cgascons** [comment] 2020-12-17 08:55
Hi Josh, I'm afraid none of the two suggestions you mentioned worked for me. I even tried increasing the memory to 4096 without luck. 

On a side note, I'm sensing like every key I type on the keyboard while in vscode attempts to search for errors and makes me think it's also affecting the whole thing, is that possible? I have made a video (and a gif) for you showing just that in case it helps, it's 44 seconds long, if you watch it, notice that around second 20 it starts checking character by character and updating the problems window:

![vscode](https://user-images.githubusercontent.com/2189330/102465181-a3d16280-404d-11eb-900a-3671f39da799.gif)
[Video.mov.zip](https://github.com/BowlerHatLLC/vscode-as3mxml/files/5708089/Video.mov.zip)

**Comment by cgascons** [comment] 2020-12-29 15:11
Hey Josh, first of all Merry Christmas! Just wanted to update you letting you know that, this week since I'm working from home I'm lo longer using a Mac and I'm on a quite powerful PC and still having issues with this, to the point of having to restart the PC from time to time. So basically wanted to check in to see if you made any progress or you need me to do anything else besides my last post here. Just ask if you need me to do anything.

**Comment by joshtynjala** [comment] 2020-12-31 21:02
I still need someone to share a project that can reproduce the issue on one of my computers. Until that happens, I'm stuck.

**Comment by cgascons** [comment] 2021-01-07 08:54
I understand Josh, I will keep trying from time to time and will post here if I'm ever capable of creating a fully replicable project. Thanks!

**Comment by cgascons** [comment] 2021-01-22 10:07
Hi, I've got some extra information about this. I recently updated my MacOS to Big Sur, checked to see if this issue was still present and it was. After a few days playing around with the OS I created a backup of all my repos and performed a clean re-install of Big Sur from scratch to check step by step until finding the issue. 

After installing VSCode and your extension I was able to open the project. At this point there was no Java installed at all.  your extension warned me about that with the following message:

`Could not locate valid Java executable. To configure Java manually, use the as3mxml.java.path setting.`

I ignored it and moved on to see if at least the intellisense would work and it kind of did actually. No delays there. I was able to reference any class of the project right away, I should say that once I referenced a class, the extension could not access the functions and variables inside it and intellisense always prompted me with the functions and variables of the class I was referencing it from, but at least it wasn't lagging at that point.

That said, I am suspecting this has something to do perhaps with Java version? I'm using a very old (1024-RSA) certificate created back in 2012 which forces me to use Java version 1.8.0_112, which is the latest that allows me to compile that certificate for our Android and Steam version of the game. I have not tried to install a newer version of Java and check if the error persists but I just thought this info would be useful.

**Comment by joshtynjala** [comment] 2021-01-22 17:00
> the extension could not access the functions and variables inside it and intellisense always prompted me with the functions and variables of the class I was referencing it from

I think that this is VSCode's default IntelliSense, which literally just suggests strings from the same file and has zero understanding of the code. If vscode-as3mxml is complaining about not finding Java, then it hasn't even started up yet.

**Comment by mjesteve** [comment] 2021-06-07 00:40
Hello, 
I am experiencing a very similar problem to the one posted here at the beginning. Intellisense only works for me for a few seconds, or "that's what it seems like"?
I share it in case you can give a new clue for explanation and/or resolution:

It really "only works for a few seconds" is an "illusion". In my case, Intellisense works for me "until I open some of the files of a library I am assembling". After opening one of them, Intellisense does not work again and the typical tooltip "loading..." appears.

In my case, it is not a big project but a small one [[1]](https://github.com/mjesteve/royale-examples-community/tree/jsCalendar_Implementation), a royale example project in which I am collaborating.

It doesn't happen to me in any other project, for now. Although I think the error comes from the project itself or wk, I have tried different configurations of JAVA_TOOL_OPTIONS and as3mxml.languageServer.jvmargs but none has changed the result. I am using java 1.8.0_291 of 64

Have you found out anything during this time?

Thx.
Hiedra

**Comment by cgascons** [comment] 2021-06-07 07:47
Hi mjesteve,
We have not found any workarounds as of yet, the issue keeps happening every day but there's no way we can manage to create a replicable sample project for Josh to try it out so looks like this one's going to be a hard one to tackle.

**Comment by mjesteve** [comment] 2021-06-07 07:53
Hello cgascons,
in my project yes it can be replicated and it is small. It is in a public repo, maybe Josh can replicate it with it. Hopefully because programming like that is "somewhat complicated". If you had some time, maybe, you could try it yourself and confirm that it replicates the behavior in your system, could it be?

Hiedra.

**Comment by cgascons** [comment] 2021-06-07 07:56
> If you had some time, maybe, you could try it yourself and confirm that it replicates the behavior in your system, could it be?

I'll definitely will give it a try as soon as possible, thanks for sharing

**Comment by mjesteve** [comment] 2021-06-07 08:06
It would be great. Thank you.

**Comment by joshtynjala** [comment] 2021-06-07 15:44
@mjesteve Thanks for sharing a project! Hopefully, that will allow me to reproduce the issue. I'll let you know.

**Comment by joshtynjala** [comment] 2021-06-07 16:16
> After opening one of them, Intellisense does not work again and the typical tooltip "loading..." appears.

@mjesteve Is there a particular file that you open where it causes the issue to reproduce consistently? I did some quick tests, and unfortunately, everything seems to be working correctly on my computer.

I am not using custom values for either `JAVA_TOOL_OPTIONS` or `as3mxml.languageServer.jvmargs`. JDK 1.8.0_282 (64-bit).

**Comment by mjesteve** [comment] 2021-06-07 16:27
Hi Josh, thx.
In case it is useful I leave here my wk file : (royale-examples-community.code-workspace)

{
	"folders": [
        {
            "path": "royale-examples-community"
        },
        {
            "path": "royale-examples-community\\royaleapp\\royalejewel"
        },
        {
            "path": "royale-examples-community\\royalelibs"
        },
        {
            "path": "..\\Royale-SDK\\royale-asjs-fork\\frameworks\\projects"
        }
    ],
    "settings": {
        "as3mxml.sdk.framework": "D:\\Develop_Royale\\Projects\\Royale-SDK\\royale-asjs-fork",
        "as3mxml.sdk.editor": "D:\\Develop_Royale\\Projects\\Royale-SDK\\royale-asjs-fork"
    }
}

I have included the SDK "projects" folder for convenient debugging (actually I have it in all wk files without causing any complications other than a "warning" because the asconfig.json version specifies a deprecated 1.1 version).

I just received your last email... I attach a gif "they say a picture is worth 1000 words".

![GIF 07-06-2021 18-23-51](https://user-images.githubusercontent.com/55754195/121055533-a0799100-c7bd-11eb-836f-580d23d91a45.gif)

Can you reproduce it? JsCalendarViewYear.mxml is in the sample project and "AnnualJSCalendar.mxml" in the library. (Maybe there are errors Josh, I'm working with this control :) )

**Comment by joshtynjala** [comment] 2021-06-07 17:29
@mjesteve Thank you. Using your _.code-workspace_ file with some tweaks for different file locations on my computer, I can reproduce your issue.

If I remove the first workspace folder, the issue no longer reproduces:

```json
{
	"folders": [
        {
            "path": "royale-examples-community\\royaleapp\\royalejewel"
        },
        {
            "path": "royale-examples-community\\royalelibs"
        },
        {
            "path": "..\\Royale-SDK\\royale-asjs-fork\\frameworks\\projects"
        }
    ],
    "settings": {
        "as3mxml.sdk.framework": "D:\\Develop_Royale\\Projects\\Royale-SDK\\royale-asjs-fork",
        "as3mxml.sdk.editor": "D:\\Develop_Royale\\Projects\\Royale-SDK\\royale-asjs-fork"
    }
}
```

I think the issue is that the extension is getting confused because _royaleapp/royalejewel_ and _ royalelibs_ are child folders of _royale-examples-community_. So it is finding the same files in two different locations in a single workspace, and it doesn't seem to realize that they're the same. That's something I'll need to fix in the extension.

Until then, I recommend avoiding child folders of another folder that's already in the same workspace.

**Comment by mjesteve** [comment] 2021-06-07 18:49
Ok, "my mystery is solved" (that's why it works without problems in the other projects).
The folder "royalale-examples-community" is really left over because it contains the folder "royalelibs" which is also in the wk "royalale-examples-community "royalelibs". 
I think it's the same dog but with a different collar! (this is a spanish expression that I don't know if it will have translation in english :P )

In my case, I should leave the root directory because I have a pom that compiles the library and also compiles the main project at the same time, in the royale-examples-community folder, and although I also have another one in royalelibs that compiles all the artifacts, I don't need it that much.

With this wk structure it works fine too:
{
	"folders": [
        {
            "path": "royale-examples-community"
        },
        {
            "path": "royale-examples-community\\royaleapp\\royalejewel"
        },
        {
            "path": "royale-examples-community\\royalelibs\\royalecomponents"
        },
        {
            "path": "royale-examples-community\\royalelibs\\royalefullcalendar"
        },
        {
            "path": "royale-examples-community\\royalelibs\\royale-jscalendar"
        },
        {
            "path": "royale-examples-community\\royalelibs\\royale-js-year-calendar"
        },
        {
            "path": "royale-examples-community\\royalelibs\\royalemobiscroll"
        },
        {
            "path": "..\\Royale-SDK\\royale-asjs-fork\\frameworks\\projects"
        }
    ],
    "settings": {
        "as3mxml.sdk.framework": "D:\\Develop_Royale\\Projects\\Royale-SDK\\royale-asjs-fork",
        "as3mxml.sdk.editor": "D:\\Develop_Royale\\Projects\\Royale-SDK\\royale-asjs-fork"
    }
}

**Comment by joshtynjala** [comment] 2021-06-07 21:52
@mjesteve I fixed the bug that was causing your issue. The changes will be included in the next vscode-as3mxml update. If you want to try out the changes early, you can download a [nightly build](https://github.com/BowlerHatLLC/vscode-as3mxml/wiki/Nightly-builds-of-the-ActionScript-&-MXML-extension-for-Visual-Studio-Code).

**Comment by mjesteve** [comment] 2021-06-07 22:08
Perfect Josh.
I have installed the nightly version and added the royalelibs folder to the wp again and I have no problem with IntelliSense.

Thanks for your time.

**Closed** 2023-11-21 23:52 UTC
Labels: bug
