### ISSUE TITLE
Support for Symbols and Outline View

### ISSUE THREAD

**Issue by Harbs** [BowlerHatLLC/vscode-as3mxml#469] opened 2020-04-25 20:14 UTC
The Outline View shows "No symbols found" for .as and .mxml files.

The same issue applies to the breadcrumb view of files. Files with recognized symbols allow one to navigate the file using breadcrumbs. That cannot be done with .mxml and .as files.

It would be great if the symbols would be recognized to enable these features.

**Comment by joshtynjala** [comment] 2020-04-27 15:55
I cannot reproduce this issue. Here is a screenshot of the Outline view in a random .mxml file that I just opened in a Flex app. It also works correctly in .mxml and .as files that I opened in a Royale app.

![mxml-outline-view](https://user-images.githubusercontent.com/141885/80392564-34132b00-8864-11ea-82ac-6a3d3cab14a1.png)

The next time that it happens, can you take a look in the Output view? Select "ActionScript & MXML language server" from the drop down. If you see any stack traces or errors there, copy and paste them here. There's likely some exception happening in the compiler when parsing some of your files.

**Comment by Harbs** [comment] 2020-04-27 16:24
Huh. It's clearly not a universal problem. I now noticed that I do see the symbols in some projects, but not in others.

Not sure what the difference is between projects...

**Comment by Harbs** [comment] 2020-04-27 16:29
Huh. Now that's weird. I'm now seeing the outline everywhere. A few minutes ago I wasn't. I'll need to check my other computer.

**Comment by joshtynjala** [comment] 2020-05-05 23:02
Closing for now. Feel free to add any additional info if you figure out what's going on.

**Comment by joshtynjala** [comment] 2024-02-12 20:49
I am able to reproduce this time (with the same file where I couldn't reproduce previously). It looks like `selectionRange` is not getting calculated correctly for the root symbol of .mxml files, and this is causing VSCode to consider the entire result invalid. I think I recall VSCode giving a warning in one of its output consoles in the past, but it must have started treating this as an error at some point.

I cannot reproduce with .as files. The outline is correctly displayed for .as files, and it only affects .mxml files, as far as I can tell.

**Comment by davekomodo** [comment] 2024-02-12 20:58
Let me know if I can provide you with anymore information

**Comment by joshtynjala** [comment] 2024-02-12 21:04
Fixed. It'll be included in the next update.

**Closed** 2024-02-12 21:03 UTC
Labels: waiting-for-response
