### ISSUE TITLE
Display code hint for [Event tags

### ISSUE THREAD

**Issue by ylazy** [BowlerHatLLC/vscode-as3mxml#780] opened 2024-10-28 16:50 UTC
Hi!

Currently the extension does not display code hint for objects that have `[Event...]` tags.
Please consider to support it.

Thanks!

**Comment by joshtynjala** [comment] 2024-10-28 17:00
Can you be more specific about what you expect to see in the code hints?

**Comment by ylazy** [comment] 2024-10-29 01:57
class TextBox.as:

![TextBox](https://github.com/user-attachments/assets/92a452d5-de52-41e1-88d5-b9990f17246f)

Usage:

```as
var tb:TextBox = new TextBox();
tb.addEventListener(
```

I think there're should be a code hinting for these events when we want to use `addEventListener`/`removeEventListener` or any method that extends `addEventListener`/`removeEventListener`, such as `on`, `off`...

Thank you!

**Comment by joshtynjala** [comment] 2024-10-29 15:17
Closing as duplicate of #362

**Closed by joshtynjala** 2024-10-29 15:17 UTC
Labels: duplicate
