### ISSUE TITLE
Creating a new file (class, interface, mxml,...) is not considered by code intelligence.

### ISSUE THREAD

**Issue by carlosrovira** [BowlerHatLLC/vscode-as3mxml#461] opened 2020-03-26 16:52 UTC
Hi Josh,

If I'm working in the Jewel Library and add some class or interface, or working on TDJ and add an MXML, this file is not shown in code intelligence at that time. I need to close the VSCode window and open again and then after SDK is recognized, y can start writing and do CMD+SPACE and the new definition appears in the code intelligence dropdown.

Thanks

**Comment by joshtynjala** [comment] 2020-03-26 16:59
I am unable to reproduce this issue. I followed these steps:

1. Open the _examples/royale/TourDeJewel_ folder in VSCode.
2. In _src/main/royale/components_, create a file named _MyCustomComponent.mxml_
3. Add the minimum required code in _MyCustomComponent.mxml_ to be a valid MXML class. In this case, I made it into a Jewel `Group` component.
	```mxml
	<j:Group xmlns:fx="http://ns.adobe.com/mxml/2009"
		xmlns:j="library://ns.apache.org/royale/jewel">
	</j:Group>
	```
4. Open_src/main/royale/components/FormExample.mxml_.
5. <kbd>Ctrl</kbd>+<kbd>Space</kbd> and type _My_
6. I see `components:MyCustomComponent` available in the completion list.

**Comment by carlosrovira** [comment] 2020-03-26 17:08
Hi Josh,

I'm stumbled since is something I was experiencing from many, many time and now can't reproduce. Today I experienced doing my lastest jewel layout changes that involved creation of new classes... So let hold this issue for now and as soon as I get it again I'll check the steps done and cover here. Thanks!

**Comment by joshtynjala** [comment] 2020-03-26 17:11
When it happens again, please open the **Output** view in VSCode, and select **ActionScript & MXML Language Server** from the drop-down. If there are any errors there, please copy and paste them here.

**Comment by carlosrovira** [comment] 2020-03-31 10:53
Hi Josh,

today I found the problem again. This is what is printed in the output language server 

```
Could not find URI git:/Users/carlosrovira/Dev/Royale/Source/royale-asjs/frameworks/projects/Icons/src/main/royale/IconsClasses.as.git?%7B%22path%22%3A%22%2FUsers%2Fcarlosrovira%2FDev%2FRoyale%2FSource%2Froyale-asjs%2Fframeworks%2Fprojects%2FIcons%2Fsrc%2Fmain%2Froyale%2FIconsClasses.as%22%2C%22ref%22%3A%22%22%7D
Could not find URI git:/Users/carlosrovira/Dev/Royale/Source/royale-asjs/frameworks/projects/Icons/src/main/royale/org/apache/royale/icons/FontIconBase.as.git?%7B%22path%22%3A%22%2FUsers%2Fcarlosrovira%2FDev%2FRoyale%2FSource%2Froyale-asjs%2Fframeworks%2Fprojects%2FIcons%2Fsrc%2Fmain%2Froyale%2Forg%2Fapache%2Froyale%2Ficons%2FFontIconBase.as%22%2C%22ref%22%3A%22%22%7D
Could not find URI git:/Users/carlosrovira/Dev/Royale/Source/royale-asjs/frameworks/projects/Icons/src/main/royale/org/apache/royale/icons/FontIcon.as.git?%7B%22path%22%3A%22%2FUsers%2Fcarlosrovira%2FDev%2FRoyale%2FSource%2Froyale-asjs%2Fframeworks%2Fprojects%2FIcons%2Fsrc%2Fmain%2Froyale%2Forg%2Fapache%2Froyale%2Ficons%2FFontIcon.as%22%2C%22ref%22%3A%22%22%7D
Could not find URI git:/Users/carlosrovira/Dev/Royale/Source/royale-asjs/frameworks/projects/Icons/src/main/royale/org/apache/royale/icons/MaterialIcon.as.git?%7B%22path%22%3A%22%2FUsers%2Fcarlosrovira%2FDev%2FRoyale%2FSource%2Froyale-asjs%2Fframeworks%2Fprojects%2FIcons%2Fsrc%2Fmain%2Froyale%2Forg%2Fapache%2Froyale%2Ficons%2FMaterialIcon.as%22%2C%22ref%22%3A%22%22%7D
Could not find URI git:/Users/carlosrovira/Dev/Royale/Source/royale-asjs/frameworks/projects/Icons/src/main/royale/org/apache/royale/icons/FontAwesomeIcon.as.git?%7B%22path%22%3A%22%2FUsers%2Fcarlosrovira%2FDev%2FRoyale%2FSource%2Froyale-asjs%2Fframeworks%2Fprojects%2FIcons%2Fsrc%2Fmain%2Froyale%2Forg%2Fapache%2Froyale%2Ficons%2FFontAwesomeIcon.as%22%2C%22ref%22%3A%22%22%7D
```

Are all new classes to add font awesome support to the Icon library in Royale

Thanks

**Comment by carlosrovira** [comment] 2020-03-31 10:54
Restarting language server, seems to solve the problem.

**Comment by joshtynjala** [comment] 2020-03-31 15:52
I see that they are _git:/_ URIs. I've definitely only tested with projects that have _file:/_ URIs. I'm not sure that I know how to resolve _git:/_ URIs, but maybe the language server protocol provides an API for that. I can look into it.

However, first I need to figure out how to create/open a file in a way that VSCode would use _git:/_ instead of _file:/_. Do you know how you did that?

**Comment by carlosrovira** [comment] 2020-03-31 17:23
Hi Josh,

I must say I didn't do anything special, maybe VSCode configure in that way if detect some git. At the end, since I'm working in the asjs royale repo, when I create a file, I think VSCode do something in git, or git does something under neath when crearting a new file

**Comment by joshtynjala** [comment] 2020-03-31 18:57
I tried reproducing the "Could not find URI" message by creating new classes in some of the projects from my local royale-asjs repository, but unfortunately, I was not successful. Looking into VSCode's repository, I think I can see that these URIs are provided by VSCode's built-in Git extension, so I don't think it's a third-party extension that you have installed. However, I still haven't found a clue to indicate how to trigger this behavior.

I don't think that it will be especially difficult to support these git:/ URIs because the file system path is included in the query parameters. However, until we find a way to consistently reproduce the issue, there's not much that I can do about it yet.

**Comment by carlosrovira** [comment] 2020-03-31 23:29
Hi Josh, maybe is a bug in VSCode, and we should rise it. Do you have easy to fill an issue in VSCode and describe it properly? If not I try to do it.
Thanks for taking a look :)

**Comment by joshtynjala** [comment] 2020-04-01 15:46
I don't think that it's a bug, and I am not comfortable filing an issue until I understand how to reproduce it.

**Comment by joshtynjala** [comment] 2020-06-30 18:14
Closing for now. We can reopen in the future, if a consistent way to reproduce is found.

**Closed** 2020-06-30 18:13 UTC
