### ISSUE TITLE
Request textDocument/codeAction failed

### ISSUE THREAD

**Issue by ylazy** [BowlerHatLLC/vscode-as3mxml#693] opened 2023-06-23 04:35 UTC
I'm using the latest build (bundled-compiler + bin).

![image](https://github.com/BowlerHatLLC/vscode-as3mxml/assets/6010183/cc022c1e-311f-45ee-b76b-29c622b8619c)

[log.txt](https://github.com/BowlerHatLLC/vscode-as3mxml/files/11844010/log.txt)

**Comment by joshtynjala** [comment] 2023-06-23 15:19
> java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space

It appears that you may need to increase the maximum memory used by the extension using the [`as3mxml.languageServer.jvmargs`](https://github.com/BowlerHatLLC/vscode-as3mxml/wiki/Extension-settings#as3mxmllanguageserverjvmargs) setting. I believe you would do this by specifying Java's `-Xmx` argument. The example below sets it to 2 GB.

```
"as3mxml.languageServer.jvmargs": "-Xmx2g"
```

**Comment by ylazy** [comment] 2023-06-30 08:44
Increasing the maximum memoty used by the extension seems to fix the issue but it leads to another issue.

![image](https://github.com/BowlerHatLLC/vscode-as3mxml/assets/6010183/d454a42a-5235-40dc-8a93-0c81c0208a7d)

High CPU + RAM usage when I edit a large .as file.

**Comment by ylazy** [comment] 2023-07-10 03:37
Workaround: Restarting VSCode sometimes did, sometimes did not fix the high memory & cpu usage issue. But terminating the java se process always fixes the issue. My memory usage reduced from ~2gb to ~700mb and cpu reduced from ~100% to ~0%.

**Comment by joshtynjala** [comment] 2023-07-14 17:47
I'm guessing that this may have been caused by the linter, which I determined is pretty expensive to run, so I turned it off. Let me know if it still happens, but I'm closing for now.

**Closed by joshtynjala** 2023-07-14 17:47 UTC
