### ISSUE TITLE
copySourcePathAssets: Failed to copy file from source to destination

### ISSUE THREAD

**Issue by lonelyma1021** [BowlerHatLLC/vscode-as3mxml#343] opened 2019-03-21 06:02 UTC
I use the latest version (18.0) to compile an Adobe Air desktop project. As there are lots of files(eg. jpg, xml, png) should be copyed to output dir, I add `"copySurcePathAssets" : true`  to asconfig.json. And then I get an error "Failed to copy file from source [source-path]/.copyarea.db to destination [output-dir]/.copyarea.db" and the process terminated with exit code 1. I think it is caused by the file name. The file `.copyarea.db` is created by SCM(IBM Clear Case) in each dir of src. Is there anyway not copy these files to output dir??

**Comment by joshtynjala** [comment] 2019-03-21 15:03
Do you think that it would be enough to skip copying hidden files?

**Comment by lonelyma1021** [comment] 2019-03-22 00:46
It may works on Linux or Mac, but I'm working on Windows. The `.copyarea.db' is NOT a hidden files on Windows. BTW, even though I get the error, but the file has been copyed. I can find it in output dir. So I don't know what happend indeed.

**Comment by lonelyma1021** [comment] 2019-03-22 03:14
Something more. If I delete `.copyarea.db` from output dir then rerun compile task. I get file copy error but point to another file: "Failed to copy file from source [source-path]/config.xml to destination [output-dir]/config.xml". And the `.copyarea.db` is copyed to output dir with no error. The `config.xml` is just a simple READ ONLY xml file. So it seems like the problem is not caused by file name...

**Comment by lonelyma1021** [comment] 2019-03-22 10:08
I did more test. Even though I delete all `.copyarea.db` files from source dir, I still get file copy failed error. If I build the project with other IDE (Intellij IDEA) once, get static files (png, xml...) copyed to output dir. And then use VS Code to compile project with `copySourcePathAssets : false`, everything works fine.

**Comment by joshtynjala** [comment] 2019-03-22 16:19
So it sounds like it's having trouble copying any files in your project, and *.copyarea.db* is not the cause.

I know that Windows often has problems related to having the same file open in multiple programs. Do you have any other programs running that might be reading or writing to files that are inside your project folder during the build?

**Comment by lonelyma1021** [comment] 2019-03-24 04:15
I try to compile my project after close all other softwares, but  I still get the "failed to copy file" error. But I find a way to "solve" the problem : I add each resource floder to "files" in asconfig.json. Even I get the copy failed error, but in fact the files are already copyed to output dir. 
```
"files" : [
    "src",
    "src/config",
    "src/assets",
    "src/db"
]
```

**Comment by lonelyma1021** [comment] 2019-03-24 05:39
Well, I'm wrong. You can not simply ignore the "failed to copy file" error. Although the files are copyed to  output dir. But the compilation is NOT complete. There is no application describe xml file and no unpacked ANE files. You can not debug the program.

**Comment by lonelyma1021** [comment] 2019-03-24 06:05
Is the "copySourcePathAssets" function provided by VS Code? I can't find any code line about this function in the source of extension.

**Comment by joshtynjala** [comment] 2019-03-24 16:15
It's implemented in the asconfigc module:

https://github.com/BowlerHatLLC/vscode-as3mxml/blob/master/asconfigc/src/main/java/com/as3mxml/asconfigc/ASConfigC.java

It uses Java's standard Files.copy().

**Comment by lonelyma1021** [comment] 2019-03-25 05:16
I think I know what's happend.
I write a simple test for `Files.copy(source, target, REPLACE_EXISTING)`, it truns out that if the target file is already exist and is a READ ONLY file, the method will throw an "AccessDeniedException". 
In my project, those files (eg. jpg, xml) are all under the control of SCM, so they are all read only files. In https://github.com/BowlerHatLLC/vscode-as3mxml/blob/master/asconfigc/src/main/java/com/as3mxml/asconfigc/ASConfigC.java, line 332, we get a sourcePath from `asconfig.json` which is "src".
And then in https://github.com/BowlerHatLLC/vscode-as3mxml/blob/master/asconfigc/src/main/java/com/as3mxml/asconfigc/utils/ProjectUtils.java, line 259, we get a sourcePath too, which is also "src" (my main file is just in the src floder).
At last, in https://github.com/BowlerHatLLC/vscode-as3mxml/blob/master/asconfigc/src/main/java/com/as3mxml/asconfigc/ASConfigC.java, line 758, the `ProjectUtils.findSourcePathAssets()` return with a collection which contains two "src" value. And in the loop at line 764, it runs `copySourcePathAssetToOutputDirectory()` for "src" twice. 
It can explan why every file have copyed but we still get "Failed to copy" error. Cause they are copyed twice, and the error occur in the second time.
So will you ignore duplicated value before put hem in to `result` in  `findSourcePathAssets()` (https://github.com/BowlerHatLLC/vscode-as3mxml/blob/master/asconfigc/src/main/java/com/as3mxml/asconfigc/utils/ProjectUtils.java).
BTW, I think the same thing may happend in `copyHTMLTemplate()` and `copyAIRFiles()`, you may check it out.
I hope it can help you fix the problem. I'm looking forward the new version of the extension. 
At last, thank you for you effort to develop this extension. It's the only hope for me to sove my trouble (FB is realy poor efficiency, and IDEA is much too expensive )

**Comment by joshtynjala** [comment] 2019-03-25 15:48
Thank you, that's very useful information. I'll try to update it to remove duplicate source paths.

**Comment by joshtynjala** [comment] 2019-03-26 00:45
I assume that you didn't mean to close this.

**Comment by lonelyma1021** [comment] 2019-03-27 08:01
Now you have already know the problem and  may fix it in next version of the extension. On the other hand, I comment the source path setting in `asconfig.json`, and I can work on my project now. So I think this issue has finished it's job. It's time to close it.

**Comment by joshtynjala** [comment] 2019-03-27 09:57
I will close it after I fix it. I need it to remain open so that I don't forget about it. :)

**Closed** 2019-04-11 18:11 UTC
